import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:living_plant/user/home/PlantRecognitions/module/plantModule.dart';

class imageRecogntionProvider with ChangeNotifier {
  static XFile? _imagePicked;
  var _reepnseData;

  static Welcome? _autoData;

  Welcome? get AutogeneratedGetting => _autoData;
  XFile? get imagePickedGetting => _imagePicked;
  get gettingResponseData => _reepnseData;

  updateingImagePicked(XFile? pickedImage) {
    _imagePicked = pickedImage;
    notifyListeners();
  }

  updatingAutoGenratedData(Welcome Data) {
    _autoData = Data;
    notifyListeners();
  }

  updatetingDataResponse(responeData) {
    _reepnseData = responeData;
    notifyListeners();
  }
}
